### ISSUE TITLE
Use test domain and ip in examples

### ISSUE THREAD

**Issue by mirestrepo** [BrownUniversity/terraform-infoblox-record-a#2]
At the moment I am using jupyter.brown.edu and a random ip for testing, maybe it would be best to set up something specific for this purpose

**Comment by broestls** [comment]
My solution for this will be to use a random `inspec<random-4-alpha-characters>.juypter.brown.edu` with a non-resolvable IP (127.0.0.1). Works fine and doesn't risk stomping on something important. This solution is implemented in #10.
